openapi: 3.0.1
info:
  title: CardPayment
  description: API Definition of CardPayment
  version: 1.0.0
servers:
- url: http://localhost:8290/cardpayment
paths:
  /:
    get:
      responses:
        default:
          description: Default response
