openapi: 3.0.1
info:
  title: MobilePayment
  description: API Definition of MobilePayment
  version: 1.0.0
servers:
- url: http://localhost:8290/mobilepayment
paths:
  /:
    post:
      responses:
        default:
          description: Default response
