openapi: 3.0.1
info:
  title: QRCode
  description: API Definition of QRCode
  version: 1.0.0
servers:
- url: http://localhost:8290/gettickets
paths:
  /:
    post:
      responses:
        default:
          description: Default response
