openapi: 3.0.1
info:
  title: SendSMS
  description: API Definition of SendSMS
  version: 1.0.0
servers:
- url: http://localhost:8290/sms
paths:
  /:
    get:
      responses:
        default:
          description: Default response
